name: Dependabot Vulnerability Notifications
on: push

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Dependabot Alerts to Slack
        uses: pwned-17/dependabot-slack@v1.6.16
        with:
          token: "${{ secrets.DEPENDABOTTEST_GITHUB_TOKEN }}"
          slack_webhook: "${{ secrets.DEPENDABOTTEST_SLACK_WEBHOOK }}"
          count: 20
      - uses: octokit/request-action@v2.x
        id: get_dependabot_alert
        with:
          route: GET /repos/{owner}/{repo}/dependabot/alerts
          owner: DevOps-ManiInspire
          repo: bot-test
        env:
          GITHUB_TOKEN: ${{ secrets.DEPENDABOTTEST_GITHUB_TOKEN }}
