name: Dependabot Vulnerability Notifications
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Dependabot Alerts to Slack
        uses: kunalnagarco/action-cve@v1.13.0
        with:
          token: "${{ secrets.DEPENDABOTTEST_GITHUB_TOKEN }}"
          slack_webhook: "${{ secrets.DEPENDABOTTEST_SLACK_WEBHOOK }}"
          count: 100

