name: Send Message to Slack

on:
  push:
    branches:
      - main  # Run on main branch push
      - patch
  workflow_dispatch:  # Allow manual triggering from GitHub UI

env:
  PYTHON_VERSION: '3.10'
  DEPENDABOT_SCANNER_FILE: '.github/workflows/dependabot.py'

jobs:
  botTestRepo:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }} # Replace with your Python version
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install slack_sdk
          pip install pytz
          
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Execute Python script
        run: python ${{ env.DEPENDABOT_SCANNER_FILE }}
        env:
          WEBHOOK_URL: ${{ secrets.DEPENDABOTTEST_SLACK_WEBHOOK }}
          GITHUB_TOKEN: ${{ secrets.DEPENDABOTTEST_GITHUB_TOKEN }}
          REPO_OWNER: 'DevOps-ManiInspire'
          REPO_NAME: 'bot-test'
          VULNERABILITY_COUNT: 2
          
  orgRepoRepo:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}  # Replace with your Python version
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install slack_sdk
          pip install pytz
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Execute Python script
        run: python ${{ env.DEPENDABOT_SCANNER_FILE }}
        env:
          WEBHOOK_URL: ${{ secrets.DEPENDABOTTEST_SLACK_WEBHOOK }}
          GITHUB_TOKEN: ${{ secrets.DEPENDABOTTEST_GITHUB_TOKEN }}
          REPO_OWNER: 'DevOps-ManiInspire'
          REPO_NAME: 'repo'
          VULNERABILITY_COUNT: 2

  # Define more jobs if needed, all with 'needs: setup'

